redis:
  address: "localhost"
  port: "6379"
  channel: "messages:published"

consumers:
  count: 4
  list_name: "consumer:ids"

processor:
  processed_events_stream: "messages:processed"

log:
  level: "info"