services:
  redis-server:
    image: redis/redis-stack-server:latest
    network_mode: host
    container_name: redis-server

  redis-insight:
    image: redis/redisinsight:latest
    network_mode: host
    container_name: redis-insight
    depends_on:
      - redis-server

  prometheus:
    image: prom/prometheus
    network_mode: host
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    container_name: prometheus

  grafana:
    image: grafana/grafana-enterprise
    network_mode: host
    volumes:
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/custom.ini:/etc/grafana/custom.ini
    environment:
      - GF_PATHS_CONFIG=/etc/grafana/custom.ini
    container_name: grafana
    depends_on:
      - prometheus