{
 "title": "Redis-task metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Processed events per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(redis_task_processor_message_process_time_count[15s]))/15"
    }
   ]
  },
  {
   "title": "Processed events per second per consumer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "increase(redis_task_processor_message_process_time_count[15s])/15"
    }
   ]
  },
  {
   "title": "Message processing time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(redis_task_processor_message_process_time_bucket[15s])/15) by (le))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(redis_task_processor_message_process_time_bucket[15s])/15) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(redis_task_processor_message_process_time_bucket[15s])/15) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(redis_task_processor_message_process_time_bucket[15s])/15) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Events success rate",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(redis_task_processor_message_process_time_sum{state=\"PASS\"})",
     "legendFormat": "Successfully processed events"
    },
    {
     "expr": "sum(redis_task_processor_message_process_time_sum{state=\"FAIL\"})",
     "legendFormat": "Failed to process events"
    }
   ]
  }
 ]
}